apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: image-storage
  hostPath:
    path: /tmp/image-cache