apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base

patches:
- path: broadcaster-patch.yaml

images:
- name: PROJECT/BROADCASTER
  newName: anyasnif/broadcaster
  newTag: 84955d7127e8c898ce8f2b0bf327e2dffd63b594
- name: PROJECT/IMAGE
  newName: anyasnif/todo-app
  newTag: latest
- name: PROJECT/LOGOUTPUT
  newName: anyasnif/log-output
  newTag: a1074bd7b2323dfcad3cca562df2974932ca2e94
