apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-image-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeName: project-image-pv
