apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: todo-backend:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: project-config
            - configMapRef:
                name: todo-db-config
            - secretRef:
                name: todo-db-secret
          readinessProbe:
            httpGet:
              path: /todos
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
