apiVersion: v1
kind: Service
metadata:
  name: todo-db-svc
  namespace: project
  labels:
    app: todo-db
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: todo-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
  namespace: project
spec:
  serviceName: todo-db-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-db-config
                  key: PGUSER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: PGPASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-db-config
                  key: PGDATABASE
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
