apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project
resources:
- k8s/deployment.yaml
- k8s/service.yaml
- k8s/ingress.yaml
- k8s/persistentvolumeclaim.yaml
- k8s/db-secret.yaml
- k8s/postgres.yaml
- k8s/backup-sa.yaml
- k8s/cronjob-backup.yaml
- k8s/nats.yaml
- k8s/broadcaster-secret.yaml
- k8s/deployment-broadcaster.yaml
- k8s/deployment-log-output.yaml
- k8s/service-log-output.yaml
- k8s/configmap-log-output.yaml
images:
<<<<<<< HEAD
  - name: PROJECT/IMAGE
    newName: anyasnif/todo-app
    newTag: latest
  - name: PROJECT/BROADCASTER
    newName: anyasnif/broadcaster
    newTag: latest
=======
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/dwk-gke-501611/dwk-gke/broadcaster
  newTag: "1.0"
- name: PROJECT/IMAGE
  newName: europe-north1-docker.pkg.dev/dwk-gke-501611/dwk-gke/todo-app
  newTag: "1.5"
- name: PROJECT/LOGOUTPUT
  newName: anyasnif/log-output
  newTag: 922302154ce0f35c51739c0bd7db539b54898f09
>>>>>>> 60260b6180e373eff7f76fdca63dc64e9f70e1c7
