apiVersion: v1
kind: Secret
metadata:
  name: pingpong-db-secret
  namespace: exercises
  labels:
    app: pingpong-postgres
stringData:
  POSTGRES_USER: pingpong_user
  POSTGRES_PASSWORD: pingpong_password
  POSTGRES_DB: pingpong
